@startuml
left to right direction

class WiFiConnection {
  -ssid : const char*
  -password : const char*
  +WiFiConnection(ssid : const char*, password : const char*)
  +connect() : void
}

class TCPClient {
  -serverIP : const char*
  -serverPort : int
  -client : WiFiClient
  +TCPClient(serverIP : const char*, serverPort : int)
  +connect() : bool
  +sendData(data : String) : void
  +receiveData() : String
}

class UltrasonicSensor {
  -trigPin : int
  -echoPin : int
  +UltrasonicSensor(trigPin : int, echoPin : int)
  +getDistance() : float
}

class Led {
  -pin : int
  -state : bool
  -previousMillis : unsigned long
  -interval : const long
  +Led(pin : int, interval : long)
  +update() : void
  +turnOff() : void
}

Sensor -> UltrasonicSensor
Sensor -> WiFiConnection
Sensor -> TCPClient

Actuator -> Led
Actuator -> WiFiConnection
Actuator -> TCPClient

@enduml
